#= require_tree ./models
#= require_tree ./templates
#= require_tree ./views

#= require ./controller
#= require ./company-controller

#= require ./router
#= require ./company-router

#= require ./bootstrap
#= require tinymce/js/tinymce/tinymce.min.js
#= require tinymce/js/tinymce/themes/modern/theme.min.js

#= require tinymce/js/tinymce/plugins/anchor/plugin.min.js
#= require tinymce/js/tinymce/plugins/autolink/plugin.min.js
#= require tinymce/js/tinymce/plugins/autoresize/plugin.min.js
#= require tinymce/js/tinymce/plugins/autosave/plugin.min.js
#= require tinymce/js/tinymce/plugins/charmap/plugin.min.js
#= require tinymce/js/tinymce/plugins/code/plugin.min.js
#= require tinymce/js/tinymce/plugins/colorpicker/plugin.min.js
#= require tinymce/js/tinymce/plugins/contextmenu/plugin.min.js
#= require tinymce/js/tinymce/plugins/directionality/plugin.min.js
#= require tinymce/js/tinymce/plugins/fullpage/plugin.min.js
#= require tinymce/js/tinymce/plugins/fullscreen/plugin.min.js
#= require tinymce/js/tinymce/plugins/hr/plugin.min.js
#= require tinymce/js/tinymce/plugins/image/plugin.min.js
#= require tinymce/js/tinymce/plugins/imagetools/plugin.min.js
#= require tinymce/js/tinymce/plugins/insertdatetime/plugin.min.js
#= require tinymce/js/tinymce/plugins/layer/plugin.min.js
#= require tinymce/js/tinymce/plugins/legacyoutput/plugin.min.js
#= require tinymce/js/tinymce/plugins/link/plugin.min.js
#= require tinymce/js/tinymce/plugins/lists/plugin.min.js
#= require tinymce/js/tinymce/plugins/media/plugin.min.js
#= require tinymce/js/tinymce/plugins/paste/plugin.min.js
#= require tinymce/js/tinymce/plugins/preview/plugin.min.js
#= require tinymce/js/tinymce/plugins/searchreplace/plugin.min.js
#= require tinymce/js/tinymce/plugins/tabfocus/plugin.min.js
#= require tinymce/js/tinymce/plugins/table/plugin.min.js
#= require tinymce/js/tinymce/plugins/textcolor/plugin.min.js
#= require tinymce/js/tinymce/plugins/textpattern/plugin.min.js
#= require tinymce/js/tinymce/plugins/visualblocks/plugin.min.js
#= require tinymce/js/tinymce/plugins/visualchars/plugin.min.js
# require tinymce/js/tinymce/plugins/advlist/plugin.min.js
# require tinymce/js/tinymce/plugins/bbcode/plugin.min.js
# require tinymce/js/tinymce/plugins/codesample/plugin.min.js
# require tinymce/js/tinymce/plugins/emoticons/plugin.min.js
# require tinymce/js/tinymce/plugins/example/plugin.min.js
# require tinymce/js/tinymce/plugins/example_dependency/plugin.min.js
# require tinymce/js/tinymce/plugins/importcss/plugin.min.js
# require tinymce/js/tinymce/plugins/nonbreaking/plugin.min.js
# require tinymce/js/tinymce/plugins/noneditable/plugin.min.js
# require tinymce/js/tinymce/plugins/pagebreak/plugin.min.js
# require tinymce/js/tinymce/plugins/print/plugin.min.js
# require tinymce/js/tinymce/plugins/save/plugin.min.js
# require tinymce/js/tinymce/plugins/spellchecker/plugin.min.js
# require tinymce/js/tinymce/plugins/template/plugin.min.js
# require tinymce/js/tinymce/plugins/wordcount/plugin.min.js