class Iconto.REST.Producer extends Iconto.REST.WSModel
	@TYPE_USER = 'PRODUCER_TYPE_USER'
	@TYPE_COMPANY = 'PRODUCER_TYPE_COMPANY'
	@TYPE_SYSTEM   = 'PRODUCER_TYPE_SYSTEM'
	@TYPE_DELIVERY = 'PRODUCER_TYPE_DELIVERY'